services:
  web:
    build: .
    container_name: kallia-financa
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - .:/app
      - ../databases:/databases
    environment:
      - PYTHONUNBUFFERED=1
