# Generated by Django 6.0.5 on 2026-05-06 23:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, default='', help_text='Código do ativo (ex: PETR4, XPLG11). Pode ficar vazio para renda fixa.', max_length=20, verbose_name='Ticker')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('asset_type', models.CharField(choices=[('stock', 'Ação'), ('fii', 'Fundo Imobiliário'), ('etf', 'ETF'), ('bdr', 'BDR'), ('fixed_income', 'Renda Fixa'), ('crypto', 'Criptomoeda'), ('other', 'Outro')], default='stock', max_length=15, verbose_name='Tipo do Ativo')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Quantidade atual em carteira.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade')),
                ('average_price', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Preço médio de aquisição.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço Médio')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Taxa contratada (ex: 13.5 para 13,5% a.a.).', max_digits=8, null=True, verbose_name='Taxa (%)')),
                ('index', models.CharField(blank=True, default='', help_text='Indexador (CDI, IPCA, Prefixado, Selic).', max_length=20, verbose_name='Indexador')),
                ('maturity_date', models.DateField(blank=True, help_text='Data de vencimento do título de renda fixa.', null=True, verbose_name='Data de Vencimento')),
                ('invested_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor total aplicado (para renda fixa).', max_digits=14, verbose_name='Valor Investido')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor atualizado do investimento (cresce diariamente em renda fixa).', max_digits=14, verbose_name='Valor Atual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo em carteira?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='investments.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['asset_type', 'ticker', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_type', models.CharField(choices=[('dividend', 'Dividendo'), ('jcp', 'Juros sobre Capital Próprio'), ('income', 'Rendimento'), ('amortization', 'Amortização')], default='dividend', max_length=15, verbose_name='Tipo de Provento')),
                ('value_per_unit', models.DecimalField(blank=True, decimal_places=6, help_text='Valor do provento por cota/ação.', max_digits=12, null=True, verbose_name='Valor por Unidade')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Valor total recebido.', max_digits=14, verbose_name='Valor Total')),
                ('ex_date', models.DateField(blank=True, help_text="Data em que o ativo fica 'ex-provento'.", null=True, verbose_name='Data Ex')),
                ('payment_date', models.DateField(help_text='Data em que o provento foi pago.', verbose_name='Data de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Provento',
                'verbose_name_plural': 'Proventos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda')], max_length=5, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Preço Unitário')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Calculado automaticamente (quantidade × preço).', max_digits=14, verbose_name='Valor Total')),
                ('date', models.DateField(verbose_name='Data da Operação')),
                ('broker', models.CharField(blank=True, default='Rico', max_length=50, verbose_name='Corretora')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('b3_import', 'Importação B3'), ('rico_import', 'Importação Rico'), ('spreadsheet', 'Edição na Planilha')], default='manual', help_text='Como essa operação foi registrada.', max_length=15, verbose_name='Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
