# Generated by Django 6.0.5 on 2026-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='index',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='invested_value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='rate',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('b3_import', 'Importação B3'), ('rico_import', 'Importação Rico')], default='manual', help_text='Como essa operação foi registrada.', max_length=15, verbose_name='Origem'),
        ),
    ]
