# Generated by Django 6.0.5 on 2026-05-09 12:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_remove_asset_average_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Preço Atual'),
        ),
    ]
